package no.uio.ifi.in2000.team8.ui.theme

import androidx.compose.ui.graphics.Color

val logoLight = Color(0xFF2F3032)
val primaryLight = Color(0xFF294861)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF4E6C86)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF3A526E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF5F7694)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF1D4852)
val tertiaryContainerLight = Color(0xFF436C77)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFA33D23)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF67A5B)
val onErrorContainerLight = Color(0xFF2A0400)
val onBackgroundLight = Color(0xFF1A1C1D)
val surfaceLight = Color(0xFFFAF9FB)
val onSurfaceLight = Color(0xFF1A1C1D)
val surfaceVariantLight = Color(0xFFDFE3E9)
val onSurfaceVariantLight = Color(0xFF42474D)
val outlineLight = Color(0xFF73777D)
val outlineVariantLight = Color(0xFFC3C7CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3032)
val inverseOnSurfaceLight = Color(0xFFF1F0F3)
val inversePrimaryLight = Color(0xFFABCAE8)
val outlineLightMediumContrast = Color(0xFF5B5F65)


val primaryLightHighContrast = Color(0xFF00243B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF27465E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF07233D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2C4460)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00262F)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF1E4853)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF480A00)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF7E220A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val onBackgroundLightHighContrast = Color(0xFF1A1C1D)
val surfaceLightHighContrast = Color(0xFFFAF9FB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDFE3E9)
val onSurfaceVariantLightHighContrast = Color(0xFF202429)
val outlineLightHighContrast = Color(0xFF3E4349)
val outlineVariantLightHighContrast = Color(0xFF3E4349)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2F3032)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFDEEEFF)

val logoDark = Color(0xFFE4F0FF)
val primaryDark = Color(0xFFABCAE8)
val primaryContainerDark = Color(0xFF34526C)
val onPrimaryContainerDark = Color(0xFFE4F0FF)
val secondaryDark = Color(0xFFB0C8EA)
val onSecondaryDark = Color(0xFF18324C)
val secondaryContainerDark = Color(0xFF5F7694)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFA3CDDA)
val tertiaryContainerDark = Color(0xFF28525D)
val onTertiaryContainerDark = Color(0xFFC6F0FE)
val errorDark = Color(0xFFFFB4A2)
val onErrorDark = Color(0xFF621100)
val errorContainerDark = Color(0xFFC05237)
val onErrorContainerDark = Color(0xFFFFFFFF)
val onBackgroundDark = Color(0xFFE3E2E4)
val surfaceDark = Color(0xFF121315)
val onSurfaceDark = Color(0xFFE3E2E4)
val surfaceVariantDark = Color(0xFF42474D)
val onSurfaceVariantDark = Color(0xFFC3C7CD)
val outlineDark = Color(0xFF8D9197)
val outlineVariantDark = Color(0xFF42474D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E2E4)
val inverseOnSurfaceDark = Color(0xFF2F3032)
val inversePrimaryDark = Color(0xFF43617C)



val primaryDarkHighContrast = Color(0xFFF9FBFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFAFCEEC)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFAFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB4CDEE)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF4FCFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFA8D2DE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F8)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAAA)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val onBackgroundDarkHighContrast = Color(0xFFE3E2E4)
val surfaceDarkHighContrast = Color(0xFF121315)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF42474D)
val onSurfaceVariantDarkHighContrast = Color(0xFFF9FBFF)
val outlineDarkHighContrast = Color(0xFFC7CBD2)
val outlineVariantDarkHighContrast = Color(0xFFC7CBD2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE3E2E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF092C44)







